"""Constants"""
EKPA = "National and Kapodistrian University of Athens"

ECONOMICS_AND_POLITICAL_SCIENCES = "ECONOMICS AND POLITICAL SCIENCES"
EDUCATION = "EDUCATION"
HEALTH_SCIENCES = "HEALTH SCIENCES"
LAW = "LAW"
PHILOSOPHY = "PHILOSOPHY"
PHYSICAL_EDUCATION_AND_SPORT_SCIENCE = "PHYSICAL EDUCATION AND SPORT SCIENCE"
SCIENCE = "SCIENCE"
THEOLOGY = "THEOLOGY"
AGRICULTURAL_DEVELOPMENT = "AGRICULTURAL DEVELOPMENT"
NUTRITION_AND_SUSTAINABILITY = "NUTRITION AND SUSTAINABILITY"

PROFESSOR = "Professor"
ASSOCIATE_PROFESSOR = "Associate Professor"
ASSISTANT_PROFESSOR = "Assistant Professor"
LECTURER = "Lecturer"
LABORATORY_TEACHING_STAFF = "Laboratory Teaching Staff"
PHD_CANDIDATE = "PHD Candidate"

UNIS = [EKPA]

FACULTIES = {
    "names": [
        ECONOMICS_AND_POLITICAL_SCIENCES,
        EDUCATION,
        HEALTH_SCIENCES,
        LAW,
        PHILOSOPHY,
        PHYSICAL_EDUCATION_AND_SPORT_SCIENCE,
        SCIENCE,
        THEOLOGY,
        AGRICULTURAL_DEVELOPMENT,
        NUTRITION_AND_SUSTAINABILITY,
    ],
    "weights": [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
}

SCIENTIST_TITLES = {
    "names": [
        PROFESSOR,
        ASSOCIATE_PROFESSOR,
        ASSISTANT_PROFESSOR,
        LECTURER,
        LABORATORY_TEACHING_STAFF,
        PHD_CANDIDATE,
    ],
    "weights": [0.05, 0.1, 0.15, 0.15, 0.35, 0.2]
}
